export PGUSER="postgres"
export PGPASSWORD="password"
export PGHOST="192.168.11.2"
export PGPORT="5433"
export PGDATABASE="uma_processed"
export DATABASE_URL="postgresql://${PGUSER}:${PGPASSWORD}@${PGHOST}:${PGPORT}/${PGDATABASE}"
